import { db,response,user,session,endpoint,property,member,roster,sameOrigin,body,rate,requirePermit,audit,hash,parsedDirectory } from '../../team-server';
import { validateGrants } from '../../access';
export async function GET(request:Request){return endpoint(async()=>{const u=await user(),id=new URL(request.url).searchParams.get('property')||u.userId;await session(request,u,id);const p=await property(id),m=await member(id,u.userId);requirePermit(m,'Users.Manage','',p);const members=await roster(id);const sessions=await db().prepare('SELECT id,user_id,created_at,last_seen,expires_at,revoked,agent FROM app_sessions WHERE property=? ORDER BY last_seen DESC').bind(id).all();return response({members,sessions:sessions.results});});}
export async function POST(request:Request){return endpoint(async()=>{sameOrigin(request);const u=await user(),data=await body(request,100000);await rate(u.userId,'team',30);
  if(data.action==='join'){const invite=await db().prepare("SELECT * FROM members WHERE invite_hash=? AND status='invited'").bind(await hash(String(data.token))).first<any>();if(!invite||invite.email.toLowerCase()!==u.email.toLowerCase())throw response({error:'Invitation is invalid or belongs to another account.'},403);await db().prepare("UPDATE members SET user_id=?,status='pending',invite_hash=NULL WHERE id=? AND status='invited'").bind(u.userId,invite.id).run();await audit(invite.property,'membership.requested',u.userId);return response({propertyId:invite.property,pending:true});}
  const id=String(data.propertyId||u.userId);await session(request,u,id);const p=await property(id),m=await member(id,u.userId);requirePermit(m,'Users.Manage','',p);const lease=db().prepare('INSERT INTO write_leases (id,timestamp) VALUES (?,?)').bind(id+'::'+p.revision,new Date().toISOString());const update=db().prepare('UPDATE properties SET revision=revision+1,key_epoch=key_epoch+1 WHERE id=?').bind(id);const event=db().prepare('INSERT INTO audit_events (id,owner,action,timestamp) VALUES (?,?,?,?)').bind(crypto.randomUUID(),id,'membership.'+data.action+':'+u.userId,new Date().toISOString());
  if(data.action==='invite'){if(typeof data.email!=='string'||!/^\S+@\S+\.\S+$/.test(data.email)||data.email.length>200)throw response({error:'Enter a valid email address.'},400);const token=crypto.randomUUID()+crypto.randomUUID();const existing=await db().prepare('SELECT id FROM members WHERE property=? AND lower(email)=lower(?)').bind(id,data.email).first();if(existing)throw response({error:'This email already has a membership or invitation.'},409);await db().batch([lease,db().prepare("INSERT INTO members (id,property,user_id,email,employee_id,status,grants,invite_hash,created_at) VALUES (?,?,?,?,'','invited','[]',?,?)").bind(crypto.randomUUID(),id,'',data.email,await hash(token),new Date().toISOString()),update,event]);return response({inviteUrl:new URL('/#join='+token,request.url).toString()});}
  if(data.action==='revoke-session'){const target=await db().prepare('SELECT id FROM app_sessions WHERE id=? AND property=?').bind(data.sessionId,id).first();if(!target)throw response({error:'Session not found.'},404);await db().batch([lease,db().prepare('UPDATE app_sessions SET revoked=1 WHERE id=? AND property=?').bind(data.sessionId,id),update,event]);return response({ok:true});}
  if(!['approve','disable','grants'].includes(data.action))throw response({error:'Unknown team action.'},400);if(data.userId===p.owner)throw response({error:'The owner account cannot be disabled or lose recovery authority.'},400);const target=await db().prepare('SELECT id,status FROM members WHERE property=? AND user_id=?').bind(id,data.userId).first<any>();if(!target)throw response({error:'Member not found.'},404);const grants=validateGrants(data.grants||[]);if(data.employeeId&&!parsedDirectory(p).employees.some(e=>e.id===data.employeeId))throw response({error:'Employee link does not exist.'},400);await db().batch([lease,db().prepare('UPDATE members SET status=?,grants=?,employee_id=? WHERE id=?').bind(data.action==='disable'?'disabled':'active',JSON.stringify(grants),data.employeeId||'',target.id),...(data.action==='disable'?[db().prepare('UPDATE app_sessions SET revoked=1 WHERE property=? AND user_id=?').bind(id,data.userId)]:[]),update,event]);return response({ok:true,keyEpoch:p.key_epoch+1});});}
