import { zonedInstant } from './time';
export type Row = { id: string; [key: string]: any };
export type Configuration = { name: string; timezone: string; boardPosition: string; sample?: boolean; minRestHours?: number; maxWeeklyHours?: number; departments: Row[]; positions: Row[]; shifts: Row[]; roomTypes: Row[]; staffing: Row[]; boundaries: string[]; categories: string[] };
export type State = { config: Configuration; employees: Row[]; rooms: Row[]; reporting: Row[]; availability: Row[]; passon: Row[]; checks: Row[]; training: Row[]; discipline: Row[]; schedule: Row[]; boards: Row[]; snapshots: Row[]; activity: Row[]; published: boolean; publishedWeeks?: string[]; publications?: Row[]; sample: boolean; week: string; feedback: Row[] };
export const uid = () => crypto.randomUUID();
export const today = (timezone='America/Chicago') => new Intl.DateTimeFormat('en-CA', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
export const defaults = (): Configuration => ({
  name: 'The Linden House', timezone: 'America/Chicago', boardPosition: 'attendant',
  departments: [{ id:'fo', name:'Front Office' }, { id:'hk', name:'Housekeeping' }, { id:'gs', name:'Guest Services' }],
  positions: [{ id:'agent', name:'Guest Service Agent', department:'fo' }, { id:'supervisor', name:'Front Office Supervisor', department:'fo' }, { id:'attendant', name:'Room Attendant', department:'hk' }, { id:'inspector', name:'Housekeeping Supervisor', department:'hk' }, { id:'bell', name:'Bellperson', department:'gs' }],
  shifts: [{ id:'am', name:'Morning', start:'07:00', end:'15:30', hours:8 }, { id:'mid', name:'Mid', start:'10:00', end:'18:30', hours:8 }, { id:'pm', name:'Evening', start:'15:00', end:'23:30', hours:8 }, { id:'night', name:'Overnight', start:'23:00', end:'07:30', hours:8 }],
  roomTypes: [{ id:'king', name:'Classic King', score:1 }, { id:'queen', name:'Double Queen', score:1.25 }, { id:'suite', name:'Garden Suite', score:2 }],
  staffing: [{ id:'req-am', position:'agent', shift:'am', count:2 }, { id:'req-pm', position:'agent', shift:'pm', count:2 }, { id:'req-night', position:'agent', shift:'night', count:1 }],
  boundaries:['07:00','15:00','23:00'], categories:['Guest Follow-Up','Guest Issue','Operational Issue','Room Issue','VIP / Arrival','Group / Event','Staffing Note','Pending Task','FYI','Critical / Emergency'],
});
export function monday(date = today()) { const d = new Date(date+'T12:00:00Z'); d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7)); return localDate(d); }
const localDate = (d: Date) => `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`;
export function days(start: string, n=7) { return Array.from({length:n},(_,i)=>{const d=new Date(start+'T12:00:00Z'); d.setUTCDate(d.getUTCDate()+i); return localDate(d);}); }
export function seed(): State {
  const config=defaults(); const day=today();
  const employees: Row[] = [
    {id:'e1',name:'Jamie Chen',position:'supervisor',department:'fo',qualifications:['agent','supervisor'],preferred:'am',hire:'2021-04-12',hours:40,active:true},
    {id:'e2',name:'Alex Morgan',position:'agent',department:'fo',qualifications:['agent'],preferred:'am',hire:'2022-08-01',hours:40,active:true},
    {id:'e3',name:'Sam Rivera',position:'agent',department:'fo',qualifications:['agent'],preferred:'pm',hire:'2023-01-15',hours:40,active:true},
    {id:'e4',name:'Taylor Brooks',position:'agent',department:'fo',qualifications:['agent'],preferred:'night',hire:'2022-03-08',hours:40,active:true},
    {id:'e5',name:'Jordan Lee',position:'agent',department:'fo',qualifications:['agent'],preferred:'pm',hire:'2024-06-02',hours:40,active:true},
    {id:'e6',name:'Casey Adams',position:'agent',department:'fo',qualifications:['agent'],preferred:'am',hire:'2024-11-14',hours:40,active:true},
    {id:'e7',name:'Morgan Ellis',position:'agent',department:'fo',qualifications:['agent'],preferred:'night',hire:'2025-02-20',hours:40,active:true},
    {id:'e8',name:'Sofia Martinez',position:'attendant',department:'hk',qualifications:['attendant'],preferred:'am',hire:'2021-08-08',hours:40,active:true},
    {id:'e9',name:'Emma Wilson',position:'attendant',department:'hk',qualifications:['attendant'],preferred:'am',hire:'2022-11-16',hours:40,active:true},
    {id:'e10',name:'Lily Thompson',position:'attendant',department:'hk',qualifications:['attendant'],preferred:'am',hire:'2023-05-24',hours:40,active:true},
    {id:'e11',name:'Noah Patel',position:'inspector',department:'hk',qualifications:['inspector'],preferred:'am',hire:'2020-02-01',hours:40,active:true},
    {id:'e12',name:'Avery Davis',position:'bell',department:'gs',qualifications:['bell'],preferred:'mid',hire:'2024-01-15',hours:32,active:true},
  ];
  const rooms: Row[] = Array.from({length:24},(_,i)=>({id:'r'+i,number:String((i<12?200:300)+(i%12)+1),type:i%6===0?'suite':i%3===0?'queen':'king',floor:i<12?2:3,flag:i%7===0?'Early arrival':i%5===0?'Stayover':'Departure',score:i%6===0?2:i%3===0?1.25:1}));
  const passon: Row[] = [
    {id:'p1',subject:'Early arrival · Garden Suite',description:'Arrival expected around noon. Coordinate with housekeeping and let the front desk know when the suite is ready.',category:'VIP / Arrival',room:'301',priority:'High',status:'Open',owner:'e1',due:day+'T12:00',created:day+'T08:15',history:[]},
    {id:'p2',subject:'Follow up on yesterday’s noise concern',description:'Check in after breakfast to confirm the room move resolved the concern. Keep the follow-up personal and brief.',category:'Guest Follow-Up',room:'208',priority:'High',status:'Open',owner:'e2',due:day+'T10:30',created:day+'T07:40',history:[]},
    {id:'p3',subject:'Meeting group · luggage storage',description:'Eight bags expected at the bell desk before 11 AM. Group departs at 4 PM.',category:'Group / Event',room:'',priority:'Normal',status:'In progress',owner:'e12',due:day+'T11:00',created:day+'T08:00',history:[]},
    {id:'p4',subject:'Check reading light after room service',description:'Engineering completed the repair. Confirm the light is working during the room check.',category:'Room Issue',room:'305',priority:'Normal',status:'Open',owner:'e11',due:day+'T14:00',created:day+'T08:35',history:[]},
    {id:'p5',subject:'Lobby coffee station restocked',description:'Morning stock complete. Spare cups are in the service cupboard.',category:'FYI',room:'',priority:'Low',status:'Completed',owner:'e2',due:'',created:day+'T07:10',completed:day+'T08:00',history:[{at:day+'T08:00',by:'Alex Morgan',text:'Station checked and ready.'}]},
  ];
  const state: State={ config, employees, rooms, reporting:employees.filter(e=>e.department==='fo'&&e.id!=='e1').map(e=>({id:'report-'+e.id,employee:e.id,targetType:'position',target:'supervisor'})), availability:[],passon,checks:[{id:'c1',room:'201',inspector:'e11',result:'Pass',notes:'Ready for arrival.',date:day+'T09:15',status:'Complete'},{id:'c2',room:'204',inspector:'e11',result:'Pass with correction',notes:'Replace one towel before release.',date:day+'T09:30',status:'Recheck required'},{id:'c3',room:'302',inspector:'e11',result:'Pass',notes:'All set.',date:day+'T09:45',status:'Complete'}],training:[{id:'t1',employee:'e2',subject:'Confident service recovery conversations',description:'Practice acknowledging the concern and explaining the next step clearly.',expected:'Use the acknowledge, act, follow-up approach.',response:'Practiced two examples together.',due:day,status:'Follow-up due',history:[],date:day}],discipline:[],schedule:[],boards:[],snapshots:[],activity:[{id:'a1',action:'Morning shift started',at:day+'T07:00',by:'Jamie Chen'},{id:'a2',action:'Room 201 passed inspection',at:day+'T09:15',by:'Noah Patel'},{id:'a3',action:'Housekeeping board prepared',at:day+'T08:30',by:'Noah Patel'}],published:false,sample:true,week:monday(),feedback:[] };
  state.schedule=generateSchedule(state).assignments; state.boards=balanceBoard(state); return state;
}
export function managementGraph(employees: Row[], reporting: Row[]) {
  const graph=new Map<string,string[]>();
  for(const e of employees) graph.set(e.id,reporting.filter(r=>r.employee===e.id).flatMap(r=>r.targetType==='employee'?[r.target]:employees.filter(p=>p.position===r.target&&p.active!==false).map(p=>p.id)));
  const visiting=new Set<string>(),visited=new Set<string>();
  function visit(id:string) { if(visiting.has(id)) throw new Error('Reporting relationships would create a circular management path.'); if(visited.has(id))return;visiting.add(id);for(const parent of graph.get(id)||[]) {if(!graph.has(parent))throw new Error('Reporting target does not exist.');visit(parent);}visiting.delete(id);visited.add(id); }
  graph.forEach((_,id)=>visit(id)); return graph;
}
export function lineage(employee:string,employees:Row[],reporting:Row[]) {const graph=managementGraph(employees,reporting);const result=new Set<string>();const walk=(id:string)=>{for(const p of graph.get(id)||[]){if(!result.has(p)){result.add(p);walk(p);}}};walk(employee);return [...result];}
function shiftStart(date:string,s:Row,zone:string) {return zonedInstant(date,s.start,zone);}
function shiftEnd(date:string,s:Row,zone:string) {return zonedInstant(s.end<=s.start?days(date,2)[1]:date,s.end,zone);}
export function assignmentError(state:State, employee:Row, date:string, shift:Row, position:string, existing:Row[],ignore?:string) {
  if(state.config.positions.find(p=>p.id===position)?.active===false||shift.active===false)return 'The position or shift is disabled.';
  if(employee.active===false || !(employee.qualifications||[employee.position]).includes(position))return 'Employee is not qualified for this position.';
  const endDate=shift.end<=shift.start?days(date,2)[1]:date;const matchesDate=(a:Row,day:string)=>a.date===day||Array.isArray(a.weekdays)&&a.weekdays.includes(new Date(day+'T12:00:00Z').getUTCDay())||a.from&&a.to&&day>=a.from&&day<=a.to;if(state.availability.some(a=>a.employee===employee.id&&(matchesDate(a,date)||!a.shift&&matchesDate(a,endDate))&&(!a.shift||a.shift===shift.id)&&(!a.position||a.position===position)))return 'Employee is unavailable for this shift.';
  const start=shiftStart(date,shift,state.config.timezone),end=shiftEnd(date,shift,state.config.timezone);
  for(const a of existing.filter(a=>a.employee===employee.id&&a.id!==ignore)) {const s=state.config.shifts.find(s=>s.id===a.shift);if(!s)continue;const otherStart=shiftStart(a.date,s,state.config.timezone),otherEnd=shiftEnd(a.date,s,state.config.timezone);if(start<otherEnd&&end>otherStart)return 'This overlaps another assignment.';if(a.date===date)return 'Employee already has a shift on this start date.';if(start>=otherEnd&&start-otherEnd<(state.config.minRestHours??11)*3600000||otherStart>=end&&otherStart-end<(state.config.minRestHours??11)*3600000)return `Less than ${state.config.minRestHours??11} hours between shifts.`;}
  return null;
}
export function staffingApplies(rule:Row,date:string,config:Configuration){return rule.active!==false&&config.positions.some(p=>p.id===rule.position&&p.active!==false)&&config.shifts.some(s=>s.id===rule.shift&&s.active!==false)&&(!rule.weekdays?.length||rule.weekdays.includes(new Date(date+'T12:00:00Z').getUTCDay()))&&(!rule.from||date>=rule.from)&&(!rule.to||date<=rule.to);}
export function generateSchedule(state:State,selectedDates=days(state.week)) {
  const fixed=state.schedule.filter(a=>!selectedDates.includes(a.date));const assignments:Row[]=[];const warnings:string[]=[];const hours:Record<string,number>={};let required=0;for(const a of fixed.filter(a=>days(state.week).includes(a.date)))hours[a.employee]=(hours[a.employee]||0)+Number(state.config.shifts.find(sh=>sh.id===a.shift)?.hours||0);
  for(const date of selectedDates)for(const rule of state.config.staffing.filter(r=>staffingApplies(r,date,state.config))){const shift=state.config.shifts.find(s=>s.id===rule.shift);if(!shift)continue;for(let n=0;n<rule.count;n++){required++;const candidates=state.employees.filter(e=>!assignmentError(state,e,date,shift,rule.position,[...fixed,...assignments])&& (hours[e.id]||0)+shift.hours<=Number(e.maxHours??state.config.maxWeeklyHours??40));candidates.sort((a,b)=>((a.preferred===shift.id?-10:0)+(a.preferredWeekdays?.includes(new Date(date+'T12:00:00Z').getUTCDay())?-3:0)+(hours[a.id]||0)/4)-((b.preferred===shift.id?-10:0)+(b.preferredWeekdays?.includes(new Date(date+'T12:00:00Z').getUTCDay())?-3:0)+(hours[b.id]||0)/4)||String(a.hire||'9999-12-31').localeCompare(String(b.hire||'9999-12-31')));const employee=candidates[0];if(!employee){warnings.push(`${date}: ${shift.name} needs ${state.config.positions.find(p=>p.id===rule.position)?.name||rule.position}.`);continue;}assignments.push({id:uid(),employee:employee.id,position:rule.position,date,shift:shift.id});hours[employee.id]=(hours[employee.id]||0)+shift.hours;}}
  // Repair isolated gaps by moving an earlier assignment to another qualified employee.
  // This improves coverage without weakening availability, overlap, rest or hour limits.
  for(const date of selectedDates)for(const rule of state.config.staffing.filter(r=>staffingApplies(r,date,state.config))){const shift=state.config.shifts.find(s=>s.id===rule.shift);if(!shift)continue;let filled=assignments.filter(a=>a.date===date&&a.shift===rule.shift&&a.position===rule.position).length;while(filled<rule.count){let repaired=false;for(const employee of state.employees){if(assignmentError(state,employee,date,shift,rule.position,[...fixed,...assignments]))continue;for(const moved of assignments.filter(a=>a.employee===employee.id)){const movedShift=state.config.shifts.find(sh=>sh.id===moved.shift)!;if((hours[employee.id]||0)-movedShift.hours+shift.hours>Number(employee.maxHours??state.config.maxWeeklyHours??40))continue;const remaining=[...fixed,...assignments.filter(a=>a.id!==moved.id)];const replacement=state.employees.find(e=>e.id!==employee.id&&(hours[e.id]||0)+movedShift.hours<=Number(e.maxHours??state.config.maxWeeklyHours??40)&&!assignmentError(state,e,moved.date,movedShift,moved.position,remaining));if(!replacement)continue;moved.employee=replacement.id;hours[replacement.id]=(hours[replacement.id]||0)+movedShift.hours;hours[employee.id]=(hours[employee.id]||0)-movedShift.hours+shift.hours;assignments.push({id:uid(),employee:employee.id,position:rule.position,date,shift:shift.id});repaired=true;break;}if(repaired)break;}if(!repaired)break;filled++;}}
  const finalWarnings:string[]=[];for(const date of selectedDates)for(const r of state.config.staffing.filter(r=>staffingApplies(r,date,state.config))){const filled=assignments.filter(a=>a.date===date&&a.position===r.position&&a.shift===r.shift).length;if(filled<r.count)finalWarnings.push(`${date}: ${r.count-filled} unfilled ${state.config.shifts.find(sh=>sh.id===r.shift)?.name||r.shift} shifts.`);}
  const preferred=assignments.filter(a=>state.employees.find(e=>e.id===a.employee)?.preferred===a.shift).length;
  return {assignments,warnings:finalWarnings,coverage:required?Math.round(assignments.length/required*100):100,preferenceSatisfaction:assignments.length?Math.round(preferred/assignments.length*100):100,hourWarnings:state.employees.filter(e=>e.active!==false&&(hours[e.id]||0)<Number(e.hours||0)&&state.config.staffing.some(r=>(e.qualifications||[e.position]).includes(r.position))).map(e=>`${e.name}: ${hours[e.id]||0} of ${e.hours} preferred hours.`)};
}
export function balanceBoard(state:State):Row[] {
  const attendants=state.employees.filter(e=>e.active!==false&&(e.qualifications||[e.position]).includes(state.config.boardPosition));
  // Also recognize configurable attendant positions through existing board participants.
  const eligible=attendants;
  const effectiveRooms:Row[]=state.rooms.map(r=>{const task=state.boards.find(b=>b.room===r.id);return {...r,score:task?.scoreOverride??r.score,flag:task?.flagOverride||r.flag};});
  const dormant=state.boards.filter(b=>effectiveRooms.some(r=>r.id===b.room&&r.flag==='DND')).map(b=>({...b,active:false,status:'DND'}));
  const result=state.boards.filter(b=>b.active!==false&&b.locked&&eligible.some(e=>e.id===b.employee)&&effectiveRooms.some(r=>r.id===b.room&&r.flag!=='DND')).map(b=>({...b}));
  const totals:Record<string,number>={};eligible.forEach(e=>totals[e.id]=result.filter(b=>b.employee===e.id).reduce((sum,b)=>sum+Number(effectiveRooms.find(r=>r.id===b.room)?.score??1),0));
  for(const room of [...effectiveRooms].filter(r=>r.flag!=='DND'&&!result.some(b=>b.room===r.id)).sort((a,b)=>b.score-a.score||a.floor-b.floor)){const candidates=[...eligible].sort((a,b)=>totals[a.id]-totals[b.id] || result.filter(r=>r.employee===b.id&&state.rooms.find(x=>x.id===r.room)?.floor===room.floor).length-result.filter(r=>r.employee===a.id&&state.rooms.find(x=>x.id===r.room)?.floor===room.floor).length);const e=candidates[0];if(e){result.push({...state.boards.find(b=>b.room===room.id),id:state.boards.find(b=>b.room===room.id)?.id||uid(),room:room.id,employee:e.id,active:true,locked:false,status:state.boards.find(b=>b.room===room.id)?.status==='DND'?'To clean':state.boards.find(b=>b.room===room.id)?.status||'To clean'});totals[e.id]+=Number(room.score??1);}}
  return [...result,...dormant];
}
export const importTypes:Record<string,{key:keyof State|keyof Configuration,config?:boolean,required:string[],example:Record<string,unknown>}>= {
  employees:{key:'employees',required:['id','name','department','position'],example:{id:'EMP-014',name:'Jamie Chen',department:'fo',position:'agent',qualifications:['agent'],hire:'2024-01-01',hours:40,active:true}},
  departments:{key:'departments',config:true,required:['id','name'],example:{id:'fo',name:'Front Office'}},positions:{key:'positions',config:true,required:['id','name','department'],example:{id:'agent',name:'Guest Service Agent',department:'fo'}},
  rooms:{key:'rooms',required:['id','number','type','floor','score'],example:{id:'ROOM-201',number:'201',type:'king',floor:2,score:1,flag:'Departure'}},
  roomTypes:{key:'roomTypes',config:true,required:['id','name','score'],example:{id:'king',name:'Classic King',score:1}},
  reporting:{key:'reporting',required:['id','employee','targetType','target'],example:{id:'REL-014',employee:'e2',targetType:'position',target:'supervisor'}},
  availability:{key:'availability',required:['id','employee'],example:{id:'AV-014',employee:'e2',date:today(),shift:'am'}},
  shifts:{key:'shifts',config:true,required:['id','name','start','end','hours'],example:{id:'am',name:'Morning',start:'07:00',end:'15:30',hours:8}},
  staffing:{key:'staffing',config:true,required:['id','position','shift','count'],example:{id:'REQ-014',position:'agent',shift:'am',count:2}},
};
export function validateImport(type:string,input:unknown,state:State):Row[] {
  const allowed:Record<string,string[]>={employees:['id','name','department','departments','position','qualifications','hire','hours','maxHours','preferred','preferredWeekdays','active'],departments:['id','name','active'],positions:['id','name','department','active'],rooms:['id','number','type','floor','zone','score','flag','active'],roomTypes:['id','name','score','active'],reporting:['id','employee','targetType','target'],availability:['id','employee','date','shift','position','weekdays','from','to','reason'],shifts:['id','name','start','end','hours','active'],staffing:['id','position','shift','count','weekdays','from','to','active']};
  const schema=importTypes[type];if(!schema)throw new Error('Unknown import type.');if(!Array.isArray(input)||!input.length)throw new Error('Supply a non-empty JSON array.');if(input.length>5000)throw new Error('Import up to 5,000 records at a time.');const ids=new Set<string>();
  for(const [i,r] of input.entries()){if(r&&typeof r==='object'&&Object.keys(r).some(k=>!allowed[type].includes(k)))throw new Error(`Record ${i+1}: unknown field. Use only the published import schema.`);if(Object.keys(r||{}).length>50||Object.keys(r||{}).some(k=>['__proto__','constructor','prototype'].includes(k)))throw new Error('Unexpected import fields.');if(!r||typeof r!=='object'||Array.isArray(r))throw new Error(`Record ${i+1} must be an object.`);for(const field of schema.required){if(r[field]===undefined||r[field]===null||r[field]==='')throw new Error(`Record ${i+1}: ${field} is required.`);}if(typeof r.id!=='string'||ids.has(r.id))throw new Error(`Record ${i+1}: use a unique text ID.`);ids.add(r.id);
    for(const f of ['name','number','department','position','type','employee','targetType','target','shift','date','start','end'])if(r[f]!==undefined&&typeof r[f]!=='string')throw new Error(`Record ${i+1}: ${f} must be text.`);
    for(const f of ['score','floor','hours','maxHours','count'])if(r[f]!==undefined&&(typeof r[f]!=='number'||!Number.isFinite(r[f])||r[f]<0))throw new Error(`Record ${i+1}: ${f} must be a non-negative number.`);
    if(Object.values(r).some(v=>typeof v==='string'&&v.length>2000))throw new Error(`Record ${i+1}: text is too long.`);
    if(r.qualifications!==undefined&&(!Array.isArray(r.qualifications)||r.qualifications.some((q:unknown)=>typeof q!=='string')))throw new Error(`Record ${i+1}: qualifications must be an array of position IDs.`);
    if(r.active!==undefined&&typeof r.active!=='boolean')throw new Error(`Record ${i+1}: active must be true or false.`);
    for(const f of ['start','end'])if(r[f]!==undefined&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(r[f]))throw new Error(`Record ${i+1}: ${f} must use HH:MM.`);
    if(r.date!==undefined&&!validCalendarDate(r.date))throw new Error(`Record ${i+1}: date must use YYYY-MM-DD.`);
    for(const field of ['hire','from','to'])if(r[field]&&!validCalendarDate(r[field]))throw new Error(`Record ${i+1}: invalid ${field} date.`);if(r.from&&r.to&&r.from>r.to)throw new Error(`Record ${i+1}: date range is reversed.`);if(r.weekdays!==undefined&&(!Array.isArray(r.weekdays)||r.weekdays.some((d:unknown)=>!Number.isInteger(d)||Number(d)<0||Number(d)>6)))throw new Error(`Record ${i+1}: weekdays must be numbers from 0 (Sunday) to 6 (Saturday).`);if(type==='availability'&&!r.date&&!r.weekdays?.length&&!(r.from&&r.to))throw new Error(`Record ${i+1}: provide a date, weekdays, or date range.`);if(r.departments!==undefined&&(!Array.isArray(r.departments)||r.departments.some((d:string)=>!state.config.departments.some(x=>x.id===d))))throw new Error(`Record ${i+1}: unknown department affiliation.`);
    if(type==='staffing'&&(!Number.isInteger(r.count)||r.count>100))throw new Error(`Record ${i+1}: staffing count must be a whole number.`);
    const refs:Record<string,Row[]>={department:state.config.departments,position:state.config.positions,type:state.config.roomTypes,employee:state.employees,shift:state.config.shifts};for(const [field,rows] of Object.entries(refs))if(r[field]!==undefined&&!rows.some(x=>x.id===r[field]))throw new Error(`Record ${i+1}: unknown ${field} ID ${r[field]}.`);
    if(r.qualifications?.some((q:string)=>!state.config.positions.some(p=>p.id===q)))throw new Error(`Record ${i+1}: unknown qualification.`);
    if(type==='reporting'&&!['position','employee'].includes(r.targetType))throw new Error(`Record ${i+1}: targetType must be position or employee.`);
    if(type==='reporting'&&!(r.targetType==='position'?state.config.positions:state.employees).some(x=>x.id===r.target))throw new Error(`Record ${i+1}: unknown reporting target.`);
  }
  if(type==='reporting')managementGraph(state.employees,mergeRows(state.reporting,input));return input;
}
export function mergeRows(current:Row[],incoming:Row[]) {const map=new Map(current.map(r=>[r.id,r]));incoming.forEach(r=>map.set(r.id,{...map.get(r.id),...r}));return [...map.values()];}

function validCalendarDate(value:string){try{return /^\d{4}-\d{2}-\d{2}$/.test(value)&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;}catch{return false;}}
