import { deviceStore } from './vault';
import { newIdentity, decode, seal, rewrap, resources, directory, type Identity } from './team-crypto';
import { permits,fields,type Member,type Resource,type Directory } from './access';
import type { State } from './domain';
export type TeamContext={propertyId:string;revision:number;keyEpoch:number;member:Member;members:Member[];directory:Directory;identity:Identity;unassignedRooms?:string[];known:Map<string,{resource:Resource;value:string}>};
async function api(path:string,data?:unknown){const response=await fetch(path,data===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result:any=await response.json();if(!response.ok)throw new Error(result.error||'Workspace request failed.');return result;}
export async function loadTeam(user:{id:string},legacy:()=>Promise<State>){let requested=new URLSearchParams(location.search).get('property');let remote=await api('/api/team-workspace'+(requested?'?property='+encodeURIComponent(requested):''));let identity:Identity=await deviceStore('account:'+user.id);if(remote.identity&&(!identity||identity.publicKey.n!==remote.identity.n))throw new Error('ACCOUNT_RECOVERY_REQUIRED');if(!identity){identity=await newIdentity();await deviceStore('account:'+user.id,identity);await api('/api/team-workspace',{action:'identity',publicKey:identity.publicKey});}
  const join=new URLSearchParams(location.hash.slice(1)).get('join')||new URLSearchParams(location.search).get('join');if(join){const joined=await api('/api/team',{action:'join',token:join});history.replaceState({},'', '/?property='+encodeURIComponent(joined.propertyId));throw new Error('Invitation accepted. Ask your administrator to approve your account and provision encryption access, then open '+location.origin+'/?property='+joined.propertyId);}
  let state:State;if(!remote.exists){if(requested&&requested!==user.id)throw new Error('Property not found.');state=await legacy();state.config.sample=state.sample;await api('/api/team-workspace',{action:'create',directory:directory(state),timezone:state.config.timezone,boundaries:state.config.boundaries});remote=await api('/api/team-workspace');}else state=await decode(remote.resources,identity,user.id);
  const context:TeamContext={propertyId:remote.propertyId,revision:remote.revision,keyEpoch:remote.keyEpoch,member:remote.member,members:remote.members,directory:remote.directory,identity,unassignedRooms:remote.unassignedRooms,known:new Map()};
  if(remote.exists&&remote.resources.length){for(const item of resources(state,user.id)){const resource=remote.resources.find((r:Resource)=>r.id===item.id);if(resource)context.known.set(item.id,{resource,value:JSON.stringify(item.value)});}}
  return {state,context};
}
export async function saveTeam(state:State,context:TeamContext,userId:string,force=false){const fresh=await api('/api/team-workspace?property='+encodeURIComponent(context.propertyId));if(fresh.revision!==context.revision)throw new Error('Workspace changed in another session. Your encrypted device copy is preserved. Reload, or export it before continuing.');if(force){context.revision=fresh.revision;context.members=fresh.members;context.member=fresh.member;context.keyEpoch=fresh.keyEpoch;}
  const dir=permits(context.member,'Property.Configure','',context.directory)?directory(state):context.directory;const source=resources(state,userId);const records:Resource[]=[];for(const item of source){const prior=context.known.get(item.id);if(['preferences','employeePrivate'].includes(item.field)&&!permits(context.member,fields[item.field].read,item.subject,dir))continue;if(!force&&JSON.stringify(dir)===JSON.stringify(context.directory)&&prior?.value===JSON.stringify(item.value))continue;if(item.field!=='feedback'&&!permits(context.member,fields[item.field].write,item.subject,dir)){if(!prior)continue;throw new Error('Your capability does not allow editing '+item.field+'.');}if(prior&&['snapshots','scheduleArchives'].includes(item.field)){if(prior.value!==JSON.stringify(item.value))throw new Error('Historical snapshots cannot be edited.');records.push(await rewrap(prior.resource,context.identity,context.members,userId,dir));continue;}records.push(await seal(item.value,context.identity,context.members,{id:item.id,propertyId:context.propertyId,field:item.field,subject:item.subject,revision:prior?.resource.revision||0},dir));}
  const deleted=[...context.known.keys()].filter(id=>!source.some(r=>r.id===id));const response=await fetch('/api/team-workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({propertyId:context.propertyId,revision:context.revision,records,deleted,directory:dir,timezone:state.config.timezone,boundaries:state.config.boundaries})});const result:any=await response.json();if(!response.ok)throw new Error(result.error||'Save failed.');context.revision=result.revision;context.directory=dir;for(const item of source){const encrypted=records.find(r=>r.id===item.id);if(encrypted)context.known.set(item.id,{resource:encrypted,value:JSON.stringify(item.value)});}deleted.forEach(id=>context.known.delete(id));}
export const teamApi=api;

export async function provisionHistorical(context:TeamContext,userId:string){if(!context.member.grants.some(g=>g.capability==='*'&&g.scope.type==='property'))return;const source=await api('/api/keys?property='+encodeURIComponent(context.propertyId));const records=[];for(const record of source){if(!record.wrapped[userId])continue;records.push(await rewrap(record,context.identity,context.members,userId,context.directory));}if(records.length)await api('/api/keys',{propertyId:context.propertyId,records});}
