import { createKey, encrypt, decrypt, deviceStore, encryptBackup, decryptBackup, type Envelope } from './vault';
import { fields, permits, type Member, type Resource, type Directory } from './access';
import { seed, type State, type Row, monday, today } from './domain';
export type Identity={publicKey:JsonWebKey;privateKey:CryptoKey};
const b64=(a:Uint8Array)=>{let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s);};
const from64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
export async function newIdentity():Promise<Identity>{const pair=await crypto.subtle.generateKey({name:'RSA-OAEP',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['wrapKey','unwrapKey']);return {publicKey:await crypto.subtle.exportKey('jwk',pair.publicKey),privateKey:pair.privateKey};}
export async function identityBackup(identity:Identity,password:string){const data=await encryptBackup({privateKey:await crypto.subtle.exportKey('jwk',identity.privateKey),publicKey:identity.publicKey},password);return {...data,format:'easyman-account-recovery-v1'};}
export async function restoreIdentity(data:any,password:string):Promise<Identity>{if(data.format!=='easyman-account-recovery-v1')throw new Error('Choose an EasyMan account recovery file.');const decoded:any=await decryptBackup({...data,format:'easyman-configuration-v1'},password);const privateKey=await crypto.subtle.importKey('jwk',decoded.privateKey,{name:'RSA-OAEP',hash:'SHA-256'},true,['unwrapKey']);const derived={kty:decoded.privateKey.kty,n:decoded.privateKey.n,e:decoded.privateKey.e,alg:'RSA-OAEP-256',ext:true,key_ops:['wrapKey']};if(derived.n!==decoded.publicKey.n)throw new Error('Invalid recovery key pair.');return {privateKey,publicKey:decoded.publicKey};}
export async function seal(value:unknown,identity:Identity,members:Member[],resource:Pick<Resource,'id'|'field'|'subject'|'revision'|'propertyId'>,directory:Directory):Promise<Resource>{const key=await createKey();const wrapped:Record<string,string>={};for(const member of members){if(resource.field==='feedback'?member.userId!==resource.subject:!permits(member,fields[resource.field].read,resource.subject,directory))continue;const pub=await crypto.subtle.importKey('jwk',member.publicKey,{name:'RSA-OAEP',hash:'SHA-256'},false,['wrapKey']);wrapped[member.userId]=b64(new Uint8Array(await crypto.subtle.wrapKey('raw',key,pub,{name:'RSA-OAEP'})));}return {...resource,aadVersion:1,...await encrypt(value,key,JSON.stringify([resource.propertyId||'',resource.id,resource.field,resource.subject])),wrapped};}
export async function openResource(resource:Resource,identity:Identity,userId:string){const wrapped=resource.wrapped[userId];if(!wrapped)throw new Error('This record needs an administrator to provision your key access.');const key=await crypto.subtle.unwrapKey('raw',from64(wrapped),identity.privateKey,{name:'RSA-OAEP'},'AES-GCM',false,['decrypt']);return decrypt(resource,key,resource.aadVersion?JSON.stringify([resource.propertyId||'',resource.id,resource.field,resource.subject]):undefined);}
export function directory(state:State):Directory{return {employees:state.employees.map(e=>({id:e.id,department:e.department,position:e.position,active:e.active,departments:e.departments||[e.department]})),reporting:state.reporting.map(r=>({id:r.id,employee:r.employee,targetType:r.targetType,target:r.target}))};}
export function resources(state:State,userId:string){const result:{id:string;field:string;subject:string;value:any}[]=[{id:'config',field:'config',subject:'',value:{...state.config,sample:state.sample}}];for(const e of state.employees.filter(e=>state.schedule.some(a=>a.employee===e.id)||state.config.staffing.some(r=>(e.qualifications||[e.position]).includes(r.position)))){const prior=state.publications?.find(p=>p.employee===e.id);result.push({id:'publication:'+e.id,field:'publication',subject:e.id,value:prior||{id:e.id,employee:e.id,publishedWeeks:state.publishedWeeks||(state.published?[state.week]:[])}});}for(const field of Object.keys(fields)){if(['config','publication','preferences','employeePrivate','scheduleArchives'].includes(field))continue;for(const row of (state as any)[field]||[]){if(row.serverSnapshot)continue;let resourceField=field==='snapshots'&&row.type==='schedule'?'scheduleArchives':field;let value=row;let subject=['training','discipline','schedule','availability'].includes(field)?row.employee:field==='boards'?row.employee:field==='snapshots'&&row.type==='schedule'?row.employee:field==='employees'?row.id:field==='feedback'?userId:'';if(field==='employees'){const {preferred,hours,hire,maxHours,preferredWeekdays,splitDaysOffOK}=row;value={id:row.id,name:row.name,department:row.department,departments:row.departments,position:row.position,qualifications:row.qualifications,active:row.active};if([preferred,hours,hire,maxHours,preferredWeekdays,splitDaysOffOK].some(v=>v!==undefined))result.push({id:'preferences:'+row.id,field:'preferences',subject:row.id,value:{id:row.id,preferred,hours,hire,maxHours,preferredWeekdays,splitDaysOffOK}});const known=['id','name','department','departments','position','qualifications','active','preferred','hours','hire','maxHours','preferredWeekdays','splitDaysOffOK'];const extra=Object.fromEntries(Object.entries(row).filter(([k])=>!known.includes(k)));if(Object.keys(extra).length)result.push({id:'employeePrivate:'+row.id,field:'employeePrivate',subject:row.id,value:{id:row.id,...extra}});}result.push({id:resourceField+':'+(field==='boards'?row.room:row.id),field:resourceField,subject:subject||'',value});}}return result;}
export function emptyState():State{const state=seed();for(const field of ['employees','rooms','reporting','availability','passon','checks','training','discipline','schedule','boards','snapshots','activity','feedback'])(state as any)[field]=[];state.sample=false;state.week=monday(today());state.published=false;return state;}
export async function decode(resources:Resource[],identity:Identity,userId:string){const state=emptyState();const preferences:Row[]=[];for(const resource of resources){const value:any=await openResource(resource,identity,userId);if(['training','discipline','schedule','availability','boards','publication'].includes(resource.field)&&resource.subject)value.employee=resource.subject;if(['employees','preferences','employeePrivate'].includes(resource.field))value.id=resource.subject;if(resource.field==='config')state.config=value;else if(resource.field==='publication'){if(value.employee){state.publications||=[];state.publications.push(value);}else Object.assign(state,value);}else if(['preferences','employeePrivate'].includes(resource.field))preferences.push(value);else ((state as any)[resource.field==='scheduleArchives'?'snapshots':resource.field] as Row[]).push(value);}for(const p of preferences){const e=state.employees.find(e=>e.id===p.id);if(e)Object.assign(e,p);}state.week=monday(today(state.config.timezone));if(state.publications?.length)state.publishedWeeks=state.publications[0].publishedWeeks.filter((week:string)=>state.publications!.every(p=>p.publishedWeeks.includes(week)));state.published=(state.publishedWeeks||[]).includes(state.week);state.sample=state.config.sample===true;state.activity.sort((a,b)=>String(b.at).localeCompare(String(a.at)));state.passon.sort((a,b)=>String(b.created).localeCompare(String(a.created)));state.checks.sort((a,b)=>String(b.date).localeCompare(String(a.date)));state.snapshots.sort((a,b)=>String(b.at).localeCompare(String(a.at)));state.employees.sort((a,b)=>String(a.name).localeCompare(String(b.name)));state.rooms.sort((a,b)=>String(a.number).localeCompare(String(b.number),undefined,{numeric:true}));return state;}

export async function rewrap(resource:Resource,identity:Identity,members:Member[],userId:string,dir:Directory){const key=await crypto.subtle.unwrapKey('raw',from64(resource.wrapped[userId]),identity.privateKey,{name:'RSA-OAEP'},'AES-GCM',true,['encrypt','decrypt']);const wrapped:Record<string,string>={};for(const m of members){if(!permits(m,fields[resource.field].read,resource.subject,dir))continue;const pub=await crypto.subtle.importKey('jwk',m.publicKey,{name:'RSA-OAEP',hash:'SHA-256'},false,['wrapKey']);wrapped[m.userId]=b64(new Uint8Array(await crypto.subtle.wrapKey('raw',key,pub,{name:'RSA-OAEP'})));}return {...resource,wrapped};}
