import { env } from 'cloudflare:workers';
import { getChatGPTUser } from './chatgpt-auth';
import { fields, permits, validateGrants, type Directory, type Member, type Resource } from './access';
import { managementGraph } from './domain';
export const db=()=>env.DB!;
export const response=(body:unknown,status=200,headers:Record<string,string>={})=>Response.json(body,{status,headers:{'Cache-Control':'no-store',...headers}});
export async function hash(text:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(b=>b.toString(16).padStart(2,'0')).join('');}
export function sameOrigin(request:Request){if(request.headers.get('origin')!==new URL(request.url).origin)throw response({error:'Invalid request origin.'},403);}
export async function body(request:Request,max=2500000){if(Number(request.headers.get('content-length')||0)>max)throw response({error:'Request is too large.'},413);const reader=request.body?.getReader();let raw='',bytes=0;const decoder=new TextDecoder();if(reader){for(;;){const chunk=await reader.read();if(chunk.done)break;bytes+=chunk.value.byteLength;if(bytes>max){await reader.cancel();throw response({error:'Request is too large.'},413);}raw+=decoder.decode(chunk.value,{stream:true});}raw+=decoder.decode();}try{return JSON.parse(raw);}catch{throw response({error:'Invalid JSON.'},400);}}
export async function user(){const u=await getChatGPTUser();if(!u)throw response({error:'Sign in required.'},401);return u;}
export async function rate(userId:string,action:string,limit=120){const bucket=Math.floor(Date.now()/60000),id=userId+':'+action+':'+bucket;const r=await db().prepare('INSERT INTO rate_limits (id,count,expires_at) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(id,Date.now()+120000).first<{count:number}>();if(bucket%10===0)await db().prepare('DELETE FROM rate_limits WHERE expires_at<?').bind(Date.now()).run();if((r?.count||0)>limit)throw response({error:'Too many requests. Please wait a minute.'},429);}
export async function audit(owner:string,action:string,actor:string){await db().prepare('INSERT INTO audit_events (id,owner,action,timestamp) VALUES (?,?,?,?)').bind(crypto.randomUUID(),owner,action+':'+actor,new Date().toISOString()).run();}
export function validPublicKey(value:any){if(!value||value.kty!=='RSA'||typeof value.n!=='string'||value.n.length<340||value.n.length>700||value.e!=='AQAB'||value.d||value.p||value.q)throw response({error:'Use a valid public RSA key without private key material.'},400);return {kty:'RSA',n:value.n,e:value.e,alg:'RSA-OAEP-256',ext:true,key_ops:['wrapKey']};}
export async function property(id:string){const p=await db().prepare('SELECT * FROM properties WHERE id=?').bind(id).first<any>();if(!p)throw response({error:'Property not found.'},404);return p;}
export async function member(propertyId:string,userId:string){const m=await db().prepare('SELECT m.*,i.public_key FROM members m LEFT JOIN identities i ON i.user_id=m.user_id WHERE m.property=? AND m.user_id=?').bind(propertyId,userId).first<any>();if(!m||m.status!=='active')throw response({error:'Your property access is not active.'},403);return parsedMember(m);}
export function parsedMember(m:any):Member{return {userId:m.user_id,email:m.email,employeeId:m.employee_id,status:m.status,grants:JSON.parse(m.grants),publicKey:m.public_key?JSON.parse(m.public_key):null};}
export const parsedDirectory=(p:any):Directory=>JSON.parse(p.directory);
export async function roster(propertyId:string){const rows=await db().prepare('SELECT m.*,i.public_key FROM members m LEFT JOIN identities i ON i.user_id=m.user_id WHERE m.property=?').bind(propertyId).all<any>();return rows.results.map(parsedMember);}
export function requirePermit(m:Member,capability:string,subject:string,p:any){if(!permits(m,capability,subject,parsedDirectory(p)))throw response({error:'Your capability and scope do not authorize this action.'},403);}
export function validateDirectory(value:any):Directory{if(!value||!Array.isArray(value.employees)||!Array.isArray(value.reporting)||value.employees.length>5000||value.reporting.length>10000)throw response({error:'Invalid reporting directory.'},400);for(const e of value.employees)if(typeof e.id!=='string'||typeof e.department!=='string'||typeof e.position!=='string'||Object.keys(e).some(k=>!['id','department','departments','position','active'].includes(k)))throw response({error:'The scope directory must contain IDs only.'},400);managementGraph(value.employees,value.reporting);return value;}
export async function session(request:Request,u:any,propertyId:string,create=false){const cookieName='easyman_session_'+(await hash(propertyId)).slice(0,16);const token=request.headers.get('cookie')?.match(new RegExp('(?:^|;\\s*)'+cookieName+'=([^;]+)'))?.[1];if(token){const s=await db().prepare('SELECT * FROM app_sessions WHERE token_hash=? AND user_id=? AND property=?').bind(await hash(token),u.userId,propertyId).first<any>();if(s){if(s.revoked||s.expires_at<=new Date().toISOString())throw response({error:'This application session expired or was revoked. Sign out and start a new session.'},401);await db().prepare('UPDATE app_sessions SET last_seen=? WHERE id=?').bind(new Date().toISOString(),s.id).run();return {id:s.id,cookie:''};}}
  if(!create)throw response({error:'Open the property workspace before saving.'},401);const fresh=crypto.randomUUID()+crypto.randomUUID();const now=new Date().toISOString(),id=crypto.randomUUID();await db().prepare('INSERT INTO app_sessions (id,user_id,property,token_hash,created_at,last_seen,expires_at,revoked,agent) VALUES (?,?,?,?,?,?,?,0,?)').bind(id,u.userId,propertyId,await hash(fresh),now,now,new Date(Date.now()+12*3600000).toISOString(),(request.headers.get('user-agent')||'Browser').slice(0,160)).run();await audit(propertyId,'session.started',u.userId);return {id,cookie:`${cookieName}=${fresh}; Path=/; HttpOnly; SameSite=Strict; Max-Age=2592000${new URL(request.url).protocol==='https:'?'; Secure':''}`};}
export function parsedResource(r:any,userId?:string):Resource{const wrapped=JSON.parse(r.wrapped);return {propertyId:r.property||r.propertyId||'',aadVersion:r.aad||r.aadVersion||0,id:r.property?r.id.slice(r.property.length+2):r.id,field:r.field,subject:r.subject,ciphertext:r.ciphertext,iv:r.iv,revision:r.revision,wrapped:userId?{[userId]:wrapped[userId]}:wrapped};}
export async function endpoint(fn:()=>Promise<Response>){try{return await fn();}catch(e){if(e instanceof Response)return e;return response({error:e instanceof Error?e.message:'Request failed.'},400);}}
