import { registerHooks } from 'node:module';
registerHooks({resolve(specifier,context,next){return next(specifier==='./time'&&context.parentURL?.endsWith('/domain.ts')?'./time.ts':specifier,context);}});
import assert from 'node:assert/strict';
import { test } from 'node:test';
const { seed, generateSchedule, assignmentError, balanceBoard, managementGraph, lineage, validateImport, days, mergeRows } = await import('../app/domain.ts');
import { createKey, encrypt, decrypt, encryptBackup, decryptBackup } from '../app/vault.ts';
test('generated schedules satisfy qualification, availability, overlap, rest and hour limits',()=>{
  const state=seed();state.availability=[{id:'av1',employee:'e2',date:state.week}];
  const result=generateSchedule(state);const hours={};
  for(const a of result.assignments){const employee=state.employees.find(e=>e.id===a.employee),shift=state.config.shifts.find(s=>s.id===a.shift);assert.equal(assignmentError(state,employee,a.date,shift,a.position,result.assignments,a.id),null);hours[a.employee]=(hours[a.employee]||0)+shift.hours;assert.ok(hours[a.employee]<=employee.hours);}
  assert.ok(result.coverage>0);assert.ok(!result.assignments.some(a=>a.employee==='e2'&&a.date===state.week));
});
test('impossible staffing is reported as uncovered without violating hard constraints',()=>{const s=seed();s.employees=[];const result=generateSchedule(s);assert.equal(result.coverage,0);assert.equal(result.assignments.length,0);assert.equal(result.warnings.length,21);});
test('overnight rest applies across start dates',()=>{const s=seed(),e=s.employees[0];const a={id:'one',employee:e.id,date:s.week,shift:'night',position:'agent'};assert.match(assignmentError(s,e,days(s.week)[1],s.config.shifts[1],'agent',[a]),/11 hours/);});
test('board balancing preserves locks, cleaning progress and qualification',()=>{const s=seed();s.boards[0].locked=true;s.boards[1].status='Clean';const first={...s.boards[0]};const clean=s.boards[1].room;const result=balanceBoard(s);assert.deepEqual(result.find(r=>r.room===first.room),first);assert.equal(result.find(r=>r.room===clean).status,'Clean');assert.equal(new Set(result.map(r=>r.room)).size,s.rooms.length);for(const a of result)assert.ok(s.employees.find(e=>e.id===a.employee).qualifications.includes(s.config.boardPosition));const totals=s.employees.filter(e=>e.position===s.config.boardPosition).map(e=>result.filter(b=>b.employee===e.id).reduce((sum,b)=>sum+s.rooms.find(r=>r.id===b.room).score,0));assert.ok(Math.max(...totals)-Math.min(...totals)<=2);});
test('DND rooms are excluded even when previously locked',()=>{const s=seed();s.boards[0].locked=true;const room=s.rooms.find(r=>r.id===s.boards[0].room);room.flag='DND';assert.ok(!balanceBoard(s).some(b=>b.room===room.id&&b.active!==false));});
test('housekeeping qualifications follow configured IDs rather than titles',()=>{const s=seed();s.config.boardPosition='custom-cleaner';s.employees.forEach(e=>{if(e.qualifications.includes('attendant'))e.qualifications=['custom-cleaner'];});assert.equal(balanceBoard(s).length,s.rooms.length);});
test('multiple reporting paths derive lineage and reject circles',()=>{const s=seed();s.reporting.push({id:'extra',employee:'e2',targetType:'employee',target:'e11'});assert.deepEqual(new Set(lineage('e2',s.employees,s.reporting)),new Set(['e1','e11']));s.reporting.push({id:'loop',employee:'e1',targetType:'employee',target:'e2'});assert.throws(()=>managementGraph(s.employees,s.reporting),/circular/);});
test('imports reject duplicate IDs, incorrect types and unknown references',()=>{const s=seed();assert.throws(()=>validateImport('departments',[{id:'one',name:'One'},{id:'one',name:'Two'}],s),/unique/);assert.throws(()=>validateImport('rooms',[{id:'r',number:'201',type:'unknown',floor:2,score:1}],s),/unknown type/);assert.throws(()=>validateImport('staffing',[{id:'req',position:'agent',shift:'am',count:1.5}],s),/whole number/);assert.throws(()=>validateImport('employees',[{id:'emp',name:'A',department:'fo',position:'agent',active:'yes'}],s),/true or false/);});
test('merge by stable IDs preserves customization when copying defaults',()=>{assert.deepEqual(mergeRows([{id:'a',name:'Default'},{id:'b',name:'New'}],[{id:'a',name:'Custom'}]),[{id:'a',name:'Custom'},{id:'b',name:'New'}]);});
test('AES-GCM round trips and rejects incorrect keys and tampered ciphertext',async()=>{const key=await createKey(),data={private:'test-confidential-content'};const envelope=await encrypt(data,key);assert.ok(!envelope.ciphertext.includes(data.private));assert.deepEqual(await decrypt(envelope,key),data);const other=await createKey();await assert.rejects(()=>decrypt(envelope,other));await assert.rejects(()=>decrypt({...envelope,ciphertext:envelope.ciphertext.slice(0,-4)+'AAAA'},key));});
test('encrypted configuration backup requires the correct passphrase',async()=>{const config=seed().config;const backup=await encryptBackup(config,'a long test passphrase');assert.equal(backup.encrypted,true);assert.deepEqual(await decryptBackup(backup,'a long test passphrase'),config);await assert.rejects(()=>decryptBackup(backup,'wrong passphrase'));});
test('partial generation checks fixed-day assignments and preserves constraints',()=>{const s=seed();const selected=days(s.week).slice(3,5);const result=generateSchedule(s,selected);assert.ok(result.assignments.every(a=>selected.includes(a.date)));const combined=[...s.schedule.filter(a=>!selected.includes(a.date)),...result.assignments];for(const a of result.assignments)assert.equal(assignmentError(s,s.employees.find(e=>e.id===a.employee),a.date,s.config.shifts.find(sh=>sh.id===a.shift),a.position,combined,a.id),null);});
test('full-day unavailability applies to an overnight shift ending on that date',()=>{const s=seed(),date=s.week;s.availability=[{id:'vacation',employee:'e2',date:days(date,2)[1]}];assert.match(assignmentError(s,s.employees[1],date,s.config.shifts.find(sh=>sh.id==='night'),'agent',[]),/unavailable/);});
test('import rejects impossible dates and unexpected employee fields',()=>{const s=seed();assert.throws(()=>validateImport('availability',[{id:'bad',employee:'e2',date:'2026-02-31'}],s),/date/);assert.throws(()=>validateImport('employees',[{id:'bad',name:'Name',department:'fo',position:'agent',salary:100000}],s),/unknown field/);});
