import assert from 'node:assert/strict';
import { test } from 'node:test';
import { registerHooks } from 'node:module';
registerHooks({resolve(specifier,context,next){return next(specifier.startsWith('./')&&!/\.(ts|js|mjs)$/.test(specifier)&&context.parentURL?.includes('/app/')?specifier+'.ts':specifier,context);}});
const {permits,profileGrants,validateGrants}=await import('../app/access.ts');
const {newIdentity,seal,openResource,identityBackup,restoreIdentity,restoreIdentityFile,resources,directory}=await import('../app/team-crypto.ts');
const {seed}=await import('../app/domain.ts');
const {zonedInstant}=await import('../app/time.ts');
const state=seed(),dir=directory(state);
const member=(grants,employeeId='e1')=>({userId:'manager',email:'manager@example.invalid',status:'active',employeeId,grants});
test('capability and scope both apply, including reporting lineage and direct management',()=>{const m=member([{capability:'Training.View',scope:{type:'lineage'}}]);assert.equal(permits(m,'Training.View','e2',dir),true);assert.equal(permits(m,'Training.Edit','e2',dir),false);assert.equal(permits(m,'Training.View','e8',dir),false);const direct=member([{capability:'Discipline.View',scope:{type:'direct'}}]);assert.equal(permits(direct,'Discipline.View','e2',dir),true);assert.equal(permits({...direct,status:'disabled'},'Discipline.View','e2',dir),false);});
test('job titles and schedule view do not confer personnel or availability access',()=>{const m=member(profileGrants('Supervisor'));assert.equal(permits(m,'Scheduling.View','e2',dir),true);assert.equal(permits(m,'Availability.View','e2',dir),false);assert.equal(permits(m,'Training.View','e2',dir),false);assert.equal(permits(m,'Discipline.View','e2',dir),false);assert.throws(()=>validateGrants([{capability:'Training.View',scope:{type:'anything'}}]),/Invalid/);});
test('record keys are recipient-specific and omitted for unauthorized scopes',async()=>{const owner=await newIdentity(),allowed=await newIdentity(),denied=await newIdentity();const people=[{...member([{capability:'*',scope:{type:'property'}}]),userId:'owner',publicKey:owner.publicKey},{...member([{capability:'Training.View',scope:{type:'department',ids:['fo']}}]),userId:'allowed',publicKey:allowed.publicKey},{...member(profileGrants('Frontline')),userId:'denied',publicKey:denied.publicKey}];const encrypted=await seal({notes:'confidential coaching'},owner,people,{id:'training:one',field:'training',subject:'e2',revision:0},dir);assert.deepEqual(Object.keys(encrypted.wrapped).sort(),['allowed','owner']);assert.deepEqual(await openResource(encrypted,allowed,'allowed'),{notes:'confidential coaching'});await assert.rejects(()=>openResource(encrypted,denied,'allowed'));await assert.rejects(()=>openResource(encrypted,denied,'denied'));});
test('account recovery is encrypted and requires its passphrase',async()=>{const original=await newIdentity();const backup=await identityBackup(original,'a long recovery passphrase');assert.equal(backup.format,'easyman-account-recovery-v1');assert.ok(!JSON.stringify(backup).includes('privateKey'));const restored=await restoreIdentity(backup,'a long recovery passphrase');assert.equal(restored.publicKey.n,original.publicKey.n);await assert.rejects(()=>restoreIdentity(backup,'incorrect passphrase'));});
test('scheduling preferences and schedule archives use separate resources',()=>{const s=seed();s.employees[1].splitDaysOffOK=true;s.snapshots=[{id:'published',type:'schedule',items:s.schedule}];const parts=resources(s,'owner');const employee=parts.find(r=>r.id==='employees:e2');assert.equal(employee.value.preferred,undefined);assert.equal(employee.value.hire,undefined);assert.equal(employee.value.splitDaysOffOK,undefined);assert.equal(directory(s).employees[1].splitDaysOffOK,undefined);assert.equal(parts.find(r=>r.id==='preferences:e2').value.splitDaysOffOK,true);assert.ok(!parts.some(r=>r.field==='employeePrivate'&&r.subject==='e2')); assert.ok(parts.some(r=>r.id==='preferences:e2'&&r.value.hire));assert.ok(parts.some(r=>r.field==='scheduleArchives'));assert.ok(!parts.some(r=>r.field==='snapshots'&&r.value.type==='schedule'));});
test('property time zone controls instants across daylight saving changes',()=>{assert.equal(new Date(zonedInstant('2026-03-08','07:00','America/Chicago')).toISOString(),'2026-03-08T12:00:00.000Z');assert.equal(new Date(zonedInstant('2026-03-07','07:00','America/Chicago')).toISOString(),'2026-03-07T13:00:00.000Z');assert.throws(()=>zonedInstant('2026-03-08','02:30','America/Chicago'),/does not exist/);assert.equal(new Date(zonedInstant('2026-10-06','07:00','Asia/Singapore')).toISOString(),'2026-10-05T23:00:00.000Z');});
test('authenticated ciphertext rejects scope and record-identity tampering',async()=>{const identity=await newIdentity(),m={...member([{capability:'*',scope:{type:'property'}}]),userId:'owner',publicKey:identity.publicKey};const record=await seal({notes:'private'},identity,[m],{id:'training:one',propertyId:'hotel',field:'training',subject:'e2',revision:0},dir);await assert.rejects(()=>openResource({...record,subject:'e8'},identity,'owner'));await assert.rejects(()=>openResource({...record,propertyId:'another-hotel'},identity,'owner'));await assert.rejects(()=>openResource({...record,field:'passon'},identity,'owner'));});

test('recovery files give actionable errors for missing, malformed, wrong-format and incorrect-passphrase input',async()=>{await assert.rejects(()=>restoreIdentityFile('',''),/Choose your EasyMan account recovery file first/);await assert.rejects(()=>restoreIdentityFile('{','test'),/incomplete or not valid JSON/);for(const value of [null,[],{format:'easyman-configuration-v1'}])await assert.rejects(()=>restoreIdentityFile(JSON.stringify(value),'test'),/account recovery file, not a configuration/);const identity=await newIdentity(),backup=await identityBackup(identity,'test recovery passphrase'),file=JSON.stringify(backup);await assert.rejects(()=>restoreIdentityFile(file,''),/Enter the passphrase/);await assert.rejects(()=>restoreIdentityFile(file,'incorrect'),/Check its passphrase/);assert.equal((await restoreIdentityFile(file,'test recovery passphrase')).publicKey.n,identity.publicKey.n);await assert.rejects(()=>restoreIdentityFile(JSON.stringify({...backup,ciphertext:'invalid'}),'test recovery passphrase'),/make sure the file is complete/);});
